### ISSUE TITLE
Configuration on ubuntu fails

### ISSUE THREAD

**Issue by SimonNtz** [senbox-org/snap-installer#4]
Hi,

In order to use Snappy python module, I followed minutely the installation tutorial from https://senbox.atlassian.net/wiki/display/SNAP/Configure+Python+to+use+the+SNAP-Python+%28snappy%29+interface on my ubuntu 16.04 machine and it failed.

I looked at the script senbox-org/snap-installer/blob/master/files/unix/bin/snap and from my understanding the errors are triggered by the following lines:

```
clusters=`(cat "$progdir/../etc/$APPNAME".clusters; echo)

nbexec=`echo "$progdir"/../platform*/lib/nbexec`

case "`uname`" in
    Darwin*)
        eval exec sh '"$nbexec"' \
            --jdkhome '"$jdkhome"' \
            -J-Dcom.apple.mrj.application.apple.menu.about.name='"$APPNAME"' \
            -J-Xdock:name='"$APPNAME"' \
            '"-J-Xdock:icon=$progdir/../../$APPNAME.icns"' \
            --clusters '"$clusters"' \
            --userdir '"${userdir}"' \
            ${default_options} \
            "$args"

```
I search on the whole repos for a *.cluster and *nbexec* files and they just do not exist.

I am working on a project to automatize the preprocessing of Sentinel 1 TAR data. I would like to have the whole deployment on command lines therefore I am really stuck at this point. 

Your inputs to fix this this issue would help me a lot.

Cheers

Simon

**Comment by marpet** [comment]
You can't find those file in the repository. They are generated when the project is build or during the installation. 
As far as I know there are several unix users how use snappy and I guess some will use also Ubuntu 16.
So I think it must be something more specific to your system.
What is you actual error you get?

**Comment by SimonNtz** [comment]
Thank you very much for the quick reply.

I got the following error, 
`cat: /home/snap-installer/files/unix/bin/../etc/snap.clusters: No such file or directory
/home/snap-installer/files/unix/bin/snap: 1: eval: Bad substitution`

when executing,
`$./snappy-conf /usr/lib/python`

I followed the whole installation guide on the _Sentinel-1 Toolbox_ repos https://github.com/senbox-org/s1tbx at the exception of the _SNAP-DESKTOP.git_ installation that I didn't clone.

Regards

**Comment by marpet** [comment]
The problem is not only the missing desktop project but snappy-conf is intended to run on an installed SNAP and not on the checked out repositories.
maybe the guide can help you: https://senbox.atlassian.net/wiki/display/SNAP/Install+SNAP+on+the+command+line
Some one else did this to: http://forum.step.esa.int/t/install-snap-in-unattended-mode-varfile/4812

**Comment by SimonNtz** [comment]
Issue solved thanks for your reply! As you said, after the full installation of Snap the snappy configuration script worked without a single error.
